export const FETCH_BEERS = 'FETCH_BEERS';
export const BEER_SELECTED = 'BEER_SELECTED';
export const DELETE_SELECTED_BEERS = 'DELETE_SELECTED_BEERS';
export const TOGGLE_SELECT_BEERS = 'TOGGLE_SELECT_BEERS';
